/*
 * Class auto generated by TexturePacker
 *
 * Contains references to each image within the sprite sheet.
 *
 * https://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:729cd007511135809f38be6c9840ff10:cbce4ce3f8696c14eebfc391473cda25:e5b38bb9a26567b744ec8ee2f6a0215a$
 *
 */
namespace TexturePackerMonoGameDefinitions
{
	public class Flowers
	{
		public const string Flowers_0 = "flowers-0";
		public const string Flowers_1 = "flowers-1";
		public const string Flowers_2 = "flowers-2";
		public const string Flowers_3 = "flowers-3";
		public const string Flowers_4 = "flowers-4";
		public const string Flowers_5 = "flowers-5";
		public const string Flowers_6 = "flowers-6";
		public const string Flowers_7 = "flowers-7";
		public const string Flowers_8 = "flowers-8";
		public const string Flowers_9 = "flowers-9";
		public const string Flowers_10 = "flowers-10";
		public const string Flowers_11 = "flowers-11";
		public const string Flowers_12 = "flowers-12";
		public const string Flowers_13 = "flowers-13";
		public const string Flowers_14 = "flowers-14";
		public const string Flowers_15 = "flowers-15";
		public const string Flowers_16 = "flowers-16";
		public const string Flowers_17 = "flowers-17";
		public const string Flowers_18 = "flowers-18";
		public const string Flowers_19 = "flowers-19";
		public const string Flowers_20 = "flowers-20";
		public const string Flowers_21 = "flowers-21";
		public const string Flowers_22 = "flowers-22";
		public const string Flowers_23 = "flowers-23";
		public const string Flowers_24 = "flowers-24";
		public const string Flowers_25 = "flowers-25";
		public const string Flowers_26 = "flowers-26";
		public const string Flowers_27 = "flowers-27";
		public const string Flowers_28 = "flowers-28";
		public const string Flowers_29 = "flowers-29";
	}
}